// json containing all the notification content
const data = [
    {body:"Hope you have a nice day today!"},
    {body:"Today is a beautiful day to be alive!"},
    {body:"Smile, you look great!"},
    {body:"Good Morning!"},
    {body:"Everything is going to be ok :)"},
    {body:"You got this!"},
    {body:"Remember to appreciate it, before it’s too late!"},
    {body:"Keep pushing forward!"},
    {body:"You deserve happiness!"},
    {body:"You’re not stuck. You are learning, growing, and preparing to bloom!"},
    {body:"Joy over Perfection!"},
    {body:"Take a breath. It does wonders!"},
    {body:"Be the GOOD in the world!"},
    {body:"Celebrate your life!"},
    {body:"Do Justly"},
    {body:"Walk Humbly"},
    {body:"Act Aesthetically "},
    {body:"Let go and live "},
    {body:"You are loveable and capable"},
    {body:"Feeling joy"},
    {body:"Be well with your spirit"},
    {body:"Be well with your soul"},
    {body:"Be well with your heart"},
    {body:"Be well with your mind "},
    {body:"Stop looking back and start looking up"},
    {body:"Be happy"},
    {body:"Hold your head high and your heart close"},
    {body:"Eat some vitamins 😊"},
    {body:"Make sure to eat vegetables 😊"},
    {body:"Don’t forget to drink water"},
    {body:"Rise above"},
    {body:"You are a warrior"},
    {body:"You are great!"},
    {body:"You can do it!"},
    {body:"Believe in yourself"},
    {body:"You are strong!"},
    {body:"You are powerful!"},
    {body:"Make today count!"},
    {body:"Be you. Nobody does it better!"},
    {body:"Shine as bright as the sun"},
    {body:"Happy thoughts"}, 
    {body:"Smiling mind"},
    {body:"Bloom today"} 
    

    
]
export default data