// json containing all the notification content
const data = [
    "Hope you have a nice day today!",
    "Today is a beautiful day to be alive!",
    "Smile, you look great!",
    "Good Morning!",
    "Everything is going to be ok :)",
    "You got this!",
    "Remember to appreciate it, before it’s too late!",
    "Keep pushing forward!",
    "You deserve happiness!",
    "You’re not stuck. You are learning, growing, and preparing to bloom!",
    "Joy over Perfection!",
    "Take a breath. It does wonders!",
    "Be the GOOD in the world!",
    "Celebrate your life!",
    "Do Justly",
    "Walk Humbly",
    "Act Aesthetically ",
    "Let go and live ",
    "You are loveable and capable",
    "Feeling joy",
    "Be well with your spirit",
    "Be well with your soul",
    "Be well with your heart",
    "Be well with your mind ",
    "Stop looking back and start looking up",
    "Be happy",
    "Hold your head high and your heart close",
    "Eat some vitamins 😊",
    "Make sure to eat vegetables 😊",
    "Don’t forget to drink water",
    "Rise above",
    "You are a warrior",
    "You are great!",
    "You can do it!",
    "Believe in yourself",
    "You are strong!",
    "You are powerful!",
    "Make today count!",
    "Be you. Nobody does it better!",
    "Shine as bright as the sun",
    "Happy thoughts", 
    "Smiling mind",
    "Bloom today" 

]
export default data